[package]
name = "snakerace"
version = "0.1.0"
authors = ["Catalin <nomail@nomail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.131.0"
rand = "0.8.5"